version: '3'

services:
  tilka-app:
    build: .
    image: tilka
    environment:
      - DATABASE_URL=postgres://postgresuser:password@postgresdb:5432/tilka
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/tilka
    networks:
      - node-network

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: tilka
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  pgdata:

networks:
  node-network:
    driver: bridge
